travis:
  secure:
    BINSTAR_TOKEN: O8IaRJjxddeLbTs7GGIh5n5eEVE1AnNHahEFS5TgGdXNh4xhZOHxH3dH2LpZ5kwocmyOGLOp4N96GmUAWBOAn3dl/iBhQdL9zhZjQBjKXmIumx2yzr1k5sx064iN99ciSN4ueNHuq+FcTjLbWUamYyXgyt7gRoooLJKxK+diHh5/Wa//57tiHTiaOzJeVM1AqxlYIY4VwFOyTygd70yxr9HXCAYPm8GXjdOt1vAJIWH+5YNtNrXXvGLbXnqu4xKEmicK479c3oS549SU+YyqdwDxN/dD3IDDovKppQPi7VCgSWVuc398p4eSlcFxJB2OjJmJRWcyvdrLoBszZPgIYzN5T00jZxXXd720WXAWPq/RS0as+4IcPO+HjfLuob7OT0T+s0R+yPiD8Ek79VXqn6acmb5aZlIJQy0+rwVqBjgP08JxmIiQmFhsrTOmDfQxv5TKh+fIFtlbCpWcGa8yeGuAffvCv3Zma2qVofIn7cQeRvbJJ2lGD8Vcgqk1vzAiwxf4/TVbuJQzMIxS/k15LBof63mTcumuwT9a1I1SnSK7lu/FFxgAw9Tyn5d2vgV5RULJSCuKYws3A+aelfqyfoUyp9+MRUw8jV3wGxICPo4IKl5P2D9zeATg4Yw5QGw+MN2YVKqiEP5CknqtngPP/L6Vz2eIwKJ8xKUB7uYxMRo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
